### ISSUE TITLE
Returning struct with heap-allocated members by value

### ISSUE THREAD

**Issue by TytanRock** [frap129/CS451#1]
I'm not entirely sure this is safe with C's memory allocation.

```
pid_data alloc_data() {
    pid_data data;
    data.cmd = malloc(CMDLINE_MAX);
    data.state = malloc(sizeof(char));
    data.vmem = malloc(MEM_LEN_MAX);
    data.time = malloc(TIME_LEN_MAX);

/*Returns the struct by value, which means the values are copied to the underlying struct. MAYBE BAD*/
    return data;
}
```

**Comment by frap129** [comment]
I've experimented with returning the struct as a pointer, however it adds complexity and doesn't change memory use/functionality. I think that because my struct is defined to contains pointers, while the pointer may not be the same reference, it's still pointing to the same location in memory. Valgrind doesn't report any buffer overflows or leaks, so its probably fine
